// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	tado "github.com/clambin/tado"
	mock "github.com/stretchr/testify/mock"
)

// TadoGetter is an autogenerated mock type for the TadoGetter type
type TadoGetter struct {
	mock.Mock
}

type TadoGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *TadoGetter) EXPECT() *TadoGetter_Expecter {
	return &TadoGetter_Expecter{mock: &_m.Mock}
}

// GetMobileDevices provides a mock function with given fields: _a0
func (_m *TadoGetter) GetMobileDevices(_a0 context.Context) ([]tado.MobileDevice, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetMobileDevices")
	}

	var r0 []tado.MobileDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]tado.MobileDevice, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []tado.MobileDevice); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tado.MobileDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoGetter_GetMobileDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMobileDevices'
type TadoGetter_GetMobileDevices_Call struct {
	*mock.Call
}

// GetMobileDevices is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *TadoGetter_Expecter) GetMobileDevices(_a0 interface{}) *TadoGetter_GetMobileDevices_Call {
	return &TadoGetter_GetMobileDevices_Call{Call: _e.mock.On("GetMobileDevices", _a0)}
}

func (_c *TadoGetter_GetMobileDevices_Call) Run(run func(_a0 context.Context)) *TadoGetter_GetMobileDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TadoGetter_GetMobileDevices_Call) Return(_a0 []tado.MobileDevice, _a1 error) *TadoGetter_GetMobileDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoGetter_GetMobileDevices_Call) RunAndReturn(run func(context.Context) ([]tado.MobileDevice, error)) *TadoGetter_GetMobileDevices_Call {
	_c.Call.Return(run)
	return _c
}

// GetZones provides a mock function with given fields: _a0
func (_m *TadoGetter) GetZones(_a0 context.Context) (tado.Zones, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetZones")
	}

	var r0 tado.Zones
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tado.Zones, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tado.Zones); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tado.Zones)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoGetter_GetZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZones'
type TadoGetter_GetZones_Call struct {
	*mock.Call
}

// GetZones is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *TadoGetter_Expecter) GetZones(_a0 interface{}) *TadoGetter_GetZones_Call {
	return &TadoGetter_GetZones_Call{Call: _e.mock.On("GetZones", _a0)}
}

func (_c *TadoGetter_GetZones_Call) Run(run func(_a0 context.Context)) *TadoGetter_GetZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TadoGetter_GetZones_Call) Return(_a0 tado.Zones, _a1 error) *TadoGetter_GetZones_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoGetter_GetZones_Call) RunAndReturn(run func(context.Context) (tado.Zones, error)) *TadoGetter_GetZones_Call {
	_c.Call.Return(run)
	return _c
}

// NewTadoGetter creates a new instance of TadoGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTadoGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TadoGetter {
	mock := &TadoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
