dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
filename: 'mocks.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/clambin/tado-exporter/internal/cmd/monitor:
    interfaces:
      TadoClient: {}
  github.com/clambin/tado-exporter/internal/bot:
    interfaces:
      Controller: {}
      SlackSender: {}
      SocketModeHandler: {}
      TadoClient: {}
      Poller: {}
  github.com/clambin/tado-exporter/internal/controller/notifier:
    interfaces:
      SlackSender: {}
  github.com/clambin/tado-exporter/internal/controller/rules:
    interfaces:
      TadoClient: {}
