with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/tado-exporter/internal/collector:
    interfaces:
      TadoSetter:
  github.com/clambin/tado-exporter/internal/controller:
    interfaces:
      TadoSetter:
  github.com/clambin/tado-exporter/internal/controller/commands:
    interfaces:
      TadoSetter:
      Controllers:
  github.com/clambin/tado-exporter/internal/controller/slackbot:
    interfaces:
      SlackBot:
  github.com/clambin/tado-exporter/internal/controller/zone/rules:
    interfaces:
      TadoSetter:
  github.com/clambin/tado-exporter/internal/poller:
    interfaces:
      Poller:
      TadoGetter:
