{
 "title": "tado metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": {
     "query": "label_values(tado_zone_heating_percentage,zone_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"tado-monitor\"} |= `` | json"
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(tado_monitor_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (path) (tado_monitor_http_request_duration_seconds_sum / tado_monitor_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "home rules",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"tado-monitor\"} |= `` | json | type = `home`"
    }
   ]
  },
  {
   "title": "zone rules: $zone",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"tado-monitor\"} |= `` | json | zone =~ `^$zone$`"
    }
   ]
  }
 ]
}
{
 "title": "tadoº overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Room", "query": { "query": "label_values(zone_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Outside temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(tado_outside_temp_celsius)" }
   ]
  },
  {
   "title": "Solar intensity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tado_solar_intensity_percentage)",
     "legendFormat": "Solar intensity"
    }
   ]
  },
  {
   "title": "All rooms",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_zone_temperature_celsius)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Heating percentage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_zone_heating_percentage)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Heating mode",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_zone_target_manual_mode)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Mobile devices",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name) (tado_mobile_device_status)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tado_weather == 1", "legendFormat": "{{tado_weather}}" }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (tado_weather) (tado_weather)",
     "legendFormat": "{{tado_weather}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tado_home_state == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (home_state) (tado_home_state)",
     "legendFormat": "{{tado_weather}}"
    }
   ]
  },
  {
   "title": "Room",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "Room",
   "targets": [
    {}
   ]
  },
  {
   "title": "Heating - $Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(tado_zone_target_temp_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Target"
    },
    {
     "expr": "avg(tado_zone_temperature_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg(tado_zone_heating_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Heating"
    }
   ]
  },
  {
   "title": "Humidity - $Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(tado_zone_humidity_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Humidity"
    },
    {
     "expr": "avg(tado_zone_open_window_remaining{zone_name=\"$Room\"})",
     "legendFormat": "Open Window"
    }
   ]
  },
  {
   "title": "Devices status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(tado_zone_device_battery_status{zone_name=\"$Room\"})",
     "legendFormat": "Battery"
    },
    {
     "expr": "avg(tado_zone_device_connection_status{zone_name=\"$Room\"})",
     "legendFormat": "Connection"
    }
   ]
  }
 ]
}