{
 "title": "tadoº",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Room", "query": "label_values(zone_name)" }
  ]
 },
 "panels": [
  {
   "title": "Outside temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(tado_outside_temp_celsius)" }
   ]
  },
  {
   "title": "All rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_temperature_celsius)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Power state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_zone_power_state)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Heating percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (zone_name) (tado_heating_percentage)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tado_weather", "legendFormat": "{{tado_weather}}" }
   ]
  },
  { "title": "Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Room" },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(tado_zone_target_temp_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Target"
    },
    {
     "expr": "avg(tado_temperature_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg(tado_heating_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Heating"
    },
    {
     "expr": "avg(tado_humidity_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Humidity"
    }
   ]
  },
  { "title": "Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(tado_zone_target_temp_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Target"
    },
    {
     "expr": "avg(tado_temperature_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg(tado_heating_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Heating"
    },
    {
     "expr": "avg(tado_humidity_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Humidity"
    }
   ]
  },
  { "title": "Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(tado_zone_target_temp_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Target"
    },
    {
     "expr": "avg(tado_temperature_celsius{zone_name=\"$Room\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg(tado_heating_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Heating"
    },
    {
     "expr": "avg(tado_humidity_percentage{zone_name=\"$Room\"})",
     "legendFormat": "Humidity"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Outside conditions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "avg(tado_outside_temp_celsius)", "legendFormat": "Temp outside" },
    {
     "expr": "avg(tado_solar_intensity_percentage)",
     "legendFormat": "Solar intensity"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (tado_weather) (tado_weather)",
     "legendFormat": "{{tado_weather}}"
    }
   ]
  }
 ]
}