// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tado "github.com/clambin/tado/v2"
)

// TadoClient is an autogenerated mock type for the TadoClient type
type TadoClient struct {
	mock.Mock
}

type TadoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TadoClient) EXPECT() *TadoClient_Expecter {
	return &TadoClient_Expecter{mock: &_m.Mock}
}

// DeletePresenceLockWithResponse provides a mock function with given fields: ctx, homeId, reqEditors
func (_m *TadoClient) DeletePresenceLockWithResponse(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn) (*tado.DeletePresenceLockResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeletePresenceLockWithResponse")
	}

	var r0 *tado.DeletePresenceLockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) (*tado.DeletePresenceLockResponse, error)); ok {
		return rf(ctx, homeId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) *tado.DeletePresenceLockResponse); ok {
		r0 = rf(ctx, homeId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.DeletePresenceLockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_DeletePresenceLockWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePresenceLockWithResponse'
type TadoClient_DeletePresenceLockWithResponse_Call struct {
	*mock.Call
}

// DeletePresenceLockWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) DeletePresenceLockWithResponse(ctx interface{}, homeId interface{}, reqEditors ...interface{}) *TadoClient_DeletePresenceLockWithResponse_Call {
	return &TadoClient_DeletePresenceLockWithResponse_Call{Call: _e.mock.On("DeletePresenceLockWithResponse",
		append([]interface{}{ctx, homeId}, reqEditors...)...)}
}

func (_c *TadoClient_DeletePresenceLockWithResponse_Call) Run(run func(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn)) *TadoClient_DeletePresenceLockWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_DeletePresenceLockWithResponse_Call) Return(_a0 *tado.DeletePresenceLockResponse, _a1 error) *TadoClient_DeletePresenceLockWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_DeletePresenceLockWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...tado.RequestEditorFn) (*tado.DeletePresenceLockResponse, error)) *TadoClient_DeletePresenceLockWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteZoneOverlayWithResponse provides a mock function with given fields: ctx, homeId, zoneId, reqEditors
func (_m *TadoClient) DeleteZoneOverlayWithResponse(ctx context.Context, homeId int64, zoneId int, reqEditors ...tado.RequestEditorFn) (*tado.DeleteZoneOverlayResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId, zoneId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteZoneOverlayWithResponse")
	}

	var r0 *tado.DeleteZoneOverlayResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, ...tado.RequestEditorFn) (*tado.DeleteZoneOverlayResponse, error)); ok {
		return rf(ctx, homeId, zoneId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, ...tado.RequestEditorFn) *tado.DeleteZoneOverlayResponse); ok {
		r0 = rf(ctx, homeId, zoneId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.DeleteZoneOverlayResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, zoneId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_DeleteZoneOverlayWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteZoneOverlayWithResponse'
type TadoClient_DeleteZoneOverlayWithResponse_Call struct {
	*mock.Call
}

// DeleteZoneOverlayWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - zoneId int
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) DeleteZoneOverlayWithResponse(ctx interface{}, homeId interface{}, zoneId interface{}, reqEditors ...interface{}) *TadoClient_DeleteZoneOverlayWithResponse_Call {
	return &TadoClient_DeleteZoneOverlayWithResponse_Call{Call: _e.mock.On("DeleteZoneOverlayWithResponse",
		append([]interface{}{ctx, homeId, zoneId}, reqEditors...)...)}
}

func (_c *TadoClient_DeleteZoneOverlayWithResponse_Call) Run(run func(ctx context.Context, homeId int64, zoneId int, reqEditors ...tado.RequestEditorFn)) *TadoClient_DeleteZoneOverlayWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), args[2].(int), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_DeleteZoneOverlayWithResponse_Call) Return(_a0 *tado.DeleteZoneOverlayResponse, _a1 error) *TadoClient_DeleteZoneOverlayWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_DeleteZoneOverlayWithResponse_Call) RunAndReturn(run func(context.Context, int64, int, ...tado.RequestEditorFn) (*tado.DeleteZoneOverlayResponse, error)) *TadoClient_DeleteZoneOverlayWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetHomeStateWithResponse provides a mock function with given fields: ctx, homeId, reqEditors
func (_m *TadoClient) GetHomeStateWithResponse(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn) (*tado.GetHomeStateResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetHomeStateWithResponse")
	}

	var r0 *tado.GetHomeStateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetHomeStateResponse, error)); ok {
		return rf(ctx, homeId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) *tado.GetHomeStateResponse); ok {
		r0 = rf(ctx, homeId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetHomeStateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetHomeStateWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHomeStateWithResponse'
type TadoClient_GetHomeStateWithResponse_Call struct {
	*mock.Call
}

// GetHomeStateWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetHomeStateWithResponse(ctx interface{}, homeId interface{}, reqEditors ...interface{}) *TadoClient_GetHomeStateWithResponse_Call {
	return &TadoClient_GetHomeStateWithResponse_Call{Call: _e.mock.On("GetHomeStateWithResponse",
		append([]interface{}{ctx, homeId}, reqEditors...)...)}
}

func (_c *TadoClient_GetHomeStateWithResponse_Call) Run(run func(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetHomeStateWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetHomeStateWithResponse_Call) Return(_a0 *tado.GetHomeStateResponse, _a1 error) *TadoClient_GetHomeStateWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetHomeStateWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetHomeStateResponse, error)) *TadoClient_GetHomeStateWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *TadoClient) GetMeWithResponse(ctx context.Context, reqEditors ...tado.RequestEditorFn) (*tado.GetMeResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMeWithResponse")
	}

	var r0 *tado.GetMeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...tado.RequestEditorFn) (*tado.GetMeResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...tado.RequestEditorFn) *tado.GetMeResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetMeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetMeWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeWithResponse'
type TadoClient_GetMeWithResponse_Call struct {
	*mock.Call
}

// GetMeWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetMeWithResponse(ctx interface{}, reqEditors ...interface{}) *TadoClient_GetMeWithResponse_Call {
	return &TadoClient_GetMeWithResponse_Call{Call: _e.mock.On("GetMeWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *TadoClient_GetMeWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetMeWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetMeWithResponse_Call) Return(_a0 *tado.GetMeResponse, _a1 error) *TadoClient_GetMeWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetMeWithResponse_Call) RunAndReturn(run func(context.Context, ...tado.RequestEditorFn) (*tado.GetMeResponse, error)) *TadoClient_GetMeWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetMobileDevicesWithResponse provides a mock function with given fields: ctx, homeId, reqEditors
func (_m *TadoClient) GetMobileDevicesWithResponse(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn) (*tado.GetMobileDevicesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMobileDevicesWithResponse")
	}

	var r0 *tado.GetMobileDevicesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetMobileDevicesResponse, error)); ok {
		return rf(ctx, homeId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) *tado.GetMobileDevicesResponse); ok {
		r0 = rf(ctx, homeId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetMobileDevicesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetMobileDevicesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMobileDevicesWithResponse'
type TadoClient_GetMobileDevicesWithResponse_Call struct {
	*mock.Call
}

// GetMobileDevicesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetMobileDevicesWithResponse(ctx interface{}, homeId interface{}, reqEditors ...interface{}) *TadoClient_GetMobileDevicesWithResponse_Call {
	return &TadoClient_GetMobileDevicesWithResponse_Call{Call: _e.mock.On("GetMobileDevicesWithResponse",
		append([]interface{}{ctx, homeId}, reqEditors...)...)}
}

func (_c *TadoClient_GetMobileDevicesWithResponse_Call) Run(run func(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetMobileDevicesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetMobileDevicesWithResponse_Call) Return(_a0 *tado.GetMobileDevicesResponse, _a1 error) *TadoClient_GetMobileDevicesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetMobileDevicesWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetMobileDevicesResponse, error)) *TadoClient_GetMobileDevicesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetWeatherWithResponse provides a mock function with given fields: ctx, homeId, reqEditors
func (_m *TadoClient) GetWeatherWithResponse(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn) (*tado.GetWeatherResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWeatherWithResponse")
	}

	var r0 *tado.GetWeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetWeatherResponse, error)); ok {
		return rf(ctx, homeId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) *tado.GetWeatherResponse); ok {
		r0 = rf(ctx, homeId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetWeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetWeatherWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherWithResponse'
type TadoClient_GetWeatherWithResponse_Call struct {
	*mock.Call
}

// GetWeatherWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetWeatherWithResponse(ctx interface{}, homeId interface{}, reqEditors ...interface{}) *TadoClient_GetWeatherWithResponse_Call {
	return &TadoClient_GetWeatherWithResponse_Call{Call: _e.mock.On("GetWeatherWithResponse",
		append([]interface{}{ctx, homeId}, reqEditors...)...)}
}

func (_c *TadoClient_GetWeatherWithResponse_Call) Run(run func(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetWeatherWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetWeatherWithResponse_Call) Return(_a0 *tado.GetWeatherResponse, _a1 error) *TadoClient_GetWeatherWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetWeatherWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetWeatherResponse, error)) *TadoClient_GetWeatherWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneStateWithResponse provides a mock function with given fields: ctx, homeId, zoneId, reqEditors
func (_m *TadoClient) GetZoneStateWithResponse(ctx context.Context, homeId int64, zoneId int, reqEditors ...tado.RequestEditorFn) (*tado.GetZoneStateResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId, zoneId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneStateWithResponse")
	}

	var r0 *tado.GetZoneStateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, ...tado.RequestEditorFn) (*tado.GetZoneStateResponse, error)); ok {
		return rf(ctx, homeId, zoneId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, ...tado.RequestEditorFn) *tado.GetZoneStateResponse); ok {
		r0 = rf(ctx, homeId, zoneId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetZoneStateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, zoneId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetZoneStateWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneStateWithResponse'
type TadoClient_GetZoneStateWithResponse_Call struct {
	*mock.Call
}

// GetZoneStateWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - zoneId int
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetZoneStateWithResponse(ctx interface{}, homeId interface{}, zoneId interface{}, reqEditors ...interface{}) *TadoClient_GetZoneStateWithResponse_Call {
	return &TadoClient_GetZoneStateWithResponse_Call{Call: _e.mock.On("GetZoneStateWithResponse",
		append([]interface{}{ctx, homeId, zoneId}, reqEditors...)...)}
}

func (_c *TadoClient_GetZoneStateWithResponse_Call) Run(run func(ctx context.Context, homeId int64, zoneId int, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetZoneStateWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), args[2].(int), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetZoneStateWithResponse_Call) Return(_a0 *tado.GetZoneStateResponse, _a1 error) *TadoClient_GetZoneStateWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetZoneStateWithResponse_Call) RunAndReturn(run func(context.Context, int64, int, ...tado.RequestEditorFn) (*tado.GetZoneStateResponse, error)) *TadoClient_GetZoneStateWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetZonesWithResponse provides a mock function with given fields: ctx, homeId, reqEditors
func (_m *TadoClient) GetZonesWithResponse(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn) (*tado.GetZonesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetZonesWithResponse")
	}

	var r0 *tado.GetZonesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetZonesResponse, error)); ok {
		return rf(ctx, homeId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...tado.RequestEditorFn) *tado.GetZonesResponse); ok {
		r0 = rf(ctx, homeId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.GetZonesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_GetZonesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZonesWithResponse'
type TadoClient_GetZonesWithResponse_Call struct {
	*mock.Call
}

// GetZonesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) GetZonesWithResponse(ctx interface{}, homeId interface{}, reqEditors ...interface{}) *TadoClient_GetZonesWithResponse_Call {
	return &TadoClient_GetZonesWithResponse_Call{Call: _e.mock.On("GetZonesWithResponse",
		append([]interface{}{ctx, homeId}, reqEditors...)...)}
}

func (_c *TadoClient_GetZonesWithResponse_Call) Run(run func(ctx context.Context, homeId int64, reqEditors ...tado.RequestEditorFn)) *TadoClient_GetZonesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_GetZonesWithResponse_Call) Return(_a0 *tado.GetZonesResponse, _a1 error) *TadoClient_GetZonesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_GetZonesWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...tado.RequestEditorFn) (*tado.GetZonesResponse, error)) *TadoClient_GetZonesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SetPresenceLockWithResponse provides a mock function with given fields: ctx, homeId, body, reqEditors
func (_m *TadoClient) SetPresenceLockWithResponse(ctx context.Context, homeId int64, body tado.PresenceLock, reqEditors ...tado.RequestEditorFn) (*tado.SetPresenceLockResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetPresenceLockWithResponse")
	}

	var r0 *tado.SetPresenceLockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, tado.PresenceLock, ...tado.RequestEditorFn) (*tado.SetPresenceLockResponse, error)); ok {
		return rf(ctx, homeId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, tado.PresenceLock, ...tado.RequestEditorFn) *tado.SetPresenceLockResponse); ok {
		r0 = rf(ctx, homeId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.SetPresenceLockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, tado.PresenceLock, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_SetPresenceLockWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPresenceLockWithResponse'
type TadoClient_SetPresenceLockWithResponse_Call struct {
	*mock.Call
}

// SetPresenceLockWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - body tado.PresenceLock
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) SetPresenceLockWithResponse(ctx interface{}, homeId interface{}, body interface{}, reqEditors ...interface{}) *TadoClient_SetPresenceLockWithResponse_Call {
	return &TadoClient_SetPresenceLockWithResponse_Call{Call: _e.mock.On("SetPresenceLockWithResponse",
		append([]interface{}{ctx, homeId, body}, reqEditors...)...)}
}

func (_c *TadoClient_SetPresenceLockWithResponse_Call) Run(run func(ctx context.Context, homeId int64, body tado.PresenceLock, reqEditors ...tado.RequestEditorFn)) *TadoClient_SetPresenceLockWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), args[2].(tado.PresenceLock), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_SetPresenceLockWithResponse_Call) Return(_a0 *tado.SetPresenceLockResponse, _a1 error) *TadoClient_SetPresenceLockWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_SetPresenceLockWithResponse_Call) RunAndReturn(run func(context.Context, int64, tado.PresenceLock, ...tado.RequestEditorFn) (*tado.SetPresenceLockResponse, error)) *TadoClient_SetPresenceLockWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SetZoneOverlayWithResponse provides a mock function with given fields: ctx, homeId, zoneId, body, reqEditors
func (_m *TadoClient) SetZoneOverlayWithResponse(ctx context.Context, homeId int64, zoneId int, body tado.ZoneOverlay, reqEditors ...tado.RequestEditorFn) (*tado.SetZoneOverlayResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, homeId, zoneId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetZoneOverlayWithResponse")
	}

	var r0 *tado.SetZoneOverlayResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, tado.ZoneOverlay, ...tado.RequestEditorFn) (*tado.SetZoneOverlayResponse, error)); ok {
		return rf(ctx, homeId, zoneId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, tado.ZoneOverlay, ...tado.RequestEditorFn) *tado.SetZoneOverlayResponse); ok {
		r0 = rf(ctx, homeId, zoneId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tado.SetZoneOverlayResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, tado.ZoneOverlay, ...tado.RequestEditorFn) error); ok {
		r1 = rf(ctx, homeId, zoneId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TadoClient_SetZoneOverlayWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetZoneOverlayWithResponse'
type TadoClient_SetZoneOverlayWithResponse_Call struct {
	*mock.Call
}

// SetZoneOverlayWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - homeId int64
//   - zoneId int
//   - body tado.ZoneOverlay
//   - reqEditors ...tado.RequestEditorFn
func (_e *TadoClient_Expecter) SetZoneOverlayWithResponse(ctx interface{}, homeId interface{}, zoneId interface{}, body interface{}, reqEditors ...interface{}) *TadoClient_SetZoneOverlayWithResponse_Call {
	return &TadoClient_SetZoneOverlayWithResponse_Call{Call: _e.mock.On("SetZoneOverlayWithResponse",
		append([]interface{}{ctx, homeId, zoneId, body}, reqEditors...)...)}
}

func (_c *TadoClient_SetZoneOverlayWithResponse_Call) Run(run func(ctx context.Context, homeId int64, zoneId int, body tado.ZoneOverlay, reqEditors ...tado.RequestEditorFn)) *TadoClient_SetZoneOverlayWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tado.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(tado.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(tado.ZoneOverlay), variadicArgs...)
	})
	return _c
}

func (_c *TadoClient_SetZoneOverlayWithResponse_Call) Return(_a0 *tado.SetZoneOverlayResponse, _a1 error) *TadoClient_SetZoneOverlayWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TadoClient_SetZoneOverlayWithResponse_Call) RunAndReturn(run func(context.Context, int64, int, tado.ZoneOverlay, ...tado.RequestEditorFn) (*tado.SetZoneOverlayResponse, error)) *TadoClient_SetZoneOverlayWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewTadoClient creates a new instance of TadoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTadoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TadoClient {
	mock := &TadoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
