// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	poller "github.com/clambin/tado-exporter/poller"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Poller is an autogenerated mock type for the Poller type
type Poller struct {
	mock.Mock
}

// Refresh provides a mock function with given fields:
func (_m *Poller) Refresh() {
	_m.Called()
}

// Register provides a mock function with given fields: ch
func (_m *Poller) Register(ch chan *poller.Update) {
	_m.Called(ch)
}

// Run provides a mock function with given fields: ctx, interval
func (_m *Poller) Run(ctx context.Context, interval time.Duration) {
	_m.Called(ctx, interval)
}
