name: build

on:
  push:
    branches:
      - master
      - build

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go1.23
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go1.23
    with:
      image: ghcr.io/clambin/tado-monitor
      dockerfile: build/Dockerfile
