name: build

on:
  push:
    branches:
      - master
      - slackbot
  pull_request_target:
    branches-ignore:
      - master
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go122
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go122
    with:
      target: tado
      image: tado-monitor
