name: Build

on:
  push:
    branches:
    - master
    - develop
    tags:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: test
      run: |
        go test ./... -race -coverprofile=coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@v1
      with:
        file: coverage.txt
        token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: metadata
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: clambin/tado-monitor
        tag-sha: True
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}.{{patch}}
    - name: Build
      run: |
        GOOS=linux GOARCH=arm   go build -o bld/tado-monitor-linux-arm
        GOOS=linux GOARCH=amd64 go build -o bld/tado-monitor-linux-amd64
    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile
        platforms: linux/amd64,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          BUILD_VERSION=${{ steps.docker_meta.outputs.version }}
