name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go122
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go122
    with:
      target: tado
      image: tado-monitor
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@go122
