name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.17
  build:
    needs: test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.17
      target: tado-monitor
  publish:
    needs: build
    uses: clambin/workflows/.github/workflows/publish.yaml@main
