name: Vulnerabilities

on:
  push:
    branches:
      - master
      - workflows
  pull_request:
  schedule:
    - cron: '23 3 * * 6'

jobs:
  vulnerabilities:
    uses: clambin/workflows/.github/workflows/vulnerabilities.yaml@main
    with:
      go-version: 1.17
